app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

login:
    pattern:   /login
    defaults:  { _controller: FOSUserBundle:Security:login }

login_check:
    pattern:   /login_check
    defaults:  { _controller: FOSUserBundle:Security:check }

logout:
    pattern:   /logout

register:
    pattern:   /register
